---
title: "Durham NC Bicycle Safety data CodeForAmerica project"
author: "David Hopp "
date: "2016-05-09 "
output: html_document
---  

# Comparing Versions of North_Carolina_Bicycle_Crash_Data.csv.gz  
This script compares a new verion of the bicycle safety data file
North_Carolina_Bicycle_Crash_Data.csv.gz with what is already in the
R project as the data frame rawData.  

## Step 01. Load bicycleSafetyData_MD.RData  
```{r step01}
load( "bicycleSafetyData_MD.RData" )
```

## Step 2. Compare data  
```{r step02}
#
# compare current version of remote file with current contents of rawData
# an alternative is to use the compare package
#
# check to be sure rawData is there
	if ( !exists("rawData") ) {
		stop( "rawData does not exist." )
	}
	#
	# read current version of remote file
	#
	strDownload <- "CrashData.csv.gz"  
	bikeSafetyURL <- "https://github.com/BikeSafety/BikeSafety/blob/master/data/North_Carolina_Bicycle_Crash_Data.csv.gz?raw=true"
	# does URL exist and is accessible?
	if ( !RCurl::url.exists( bikeSafetyURL ) ) {
		stop( "URL does not exist or is not accessible." )
	}	
	download.file( bikeSafetyURL, strDownload, mode="wb" )
	rawDataToCompare <- read.csv( gzfile(strDownload), stringsAsFactors = FALSE )
	unlink(strDownload)
	rawDataToCompare %>% write.csv( "RawDataFromRemote.csv", row.names = FALSE )
	#
	# use simple test
	#
	if ( !exists("rawDataToCompare") ) {
		stop( "rawDataToCompare does not exist." )
	}
	#
	if (identical(rawData, rawDataToCompare) ) {
		print( "representations as data frames are identical" )
	} else {
		#
		# not identical
		# look at some possible problems
		#
		print( "rawData and rawDataToCompare are not identical." )
		#
		if ( class(rawData)!=class(rawDataToCompare) ) {
			stop( paste("class of rawDataToCompare should be data.frame but is", class(rawDataToCompare)) )
		}
		print( "class of both is data.frame" )
		#
		if ( nrow(rawData)!=nrow(rawDataToCompare) ) {
			stop( paste("nrow of rawData is", nrow(rawData), "but nrow of rawDataToCompare is", nrow(rawDataToCompare)) )
		}
		print( "nrow of both are the same" )
		#
		if ( !identical(names(rawData),names(rawDataToCompare)) ) {
			print( "column names of rawData and rawDataToCompare are different:" )
			if ( length(names(rawData)==length(rawDataToCompare)) ) {
				print( "length of names are the same" )
			} else {
				print( paste("length of names of rawData is", length(names(rawData)), 
					"but length of names of rawDataToCompare is", length(names(rawDataToCompare))) )
			}
			names(rawData)
			names(rawDataToCompare)
			stop()
		}
		print( "column names of both are the same" )
		#
		print( "no more ideas right now - look closely to find the difference")
	}
```
