# ###################################################
# rawData
names(rawData)
 [1] "FID"        "OBJECTID"   "AmbulanceR" "BikeAge_Gr" "Bike_Age"   "Bike_Alc_D" "Bike_Dir"   "Bike_Injur" "Bike_Pos"  
[10] "Bike_Race"  "Bike_Sex"   "City"       "County"     "CrashAlcoh" "CrashDay"   "Crash_Date" "Crash_Grp"  "Crash_Hour"
[19] "Crash_Loc"  "Crash_Mont" "Crash_Time" "Crash_Type" "Crash_Ty_1" "Crash_Year" "Crsh_Sevri" "Developmen" "DrvrAge_Gr"
[28] "Drvr_Age"   "Drvr_Alc_D" "Drvr_EstSp" "Drvr_Injur" "Drvr_Race"  "Drvr_Sex"   "Drvr_VehTy" "ExcsSpdInd" "Hit_Run"   
[37] "Latitude"   "Light_Cond" "Locality"   "Longitude"  "Num_Lanes"  "Num_Units"  "Rd_Charact" "Rd_Class"   "Rd_Conditi"
[46] "Rd_Config"  "Rd_Defects" "Rd_Feature" "Rd_Surface" "Region"     "Rural_Urba" "Speed_Limi" "Traff_Cntr" "Weather"   
[55] "Workzone_I" "Location"  
#
names_rawData <- names(rawData)
#
str(rawData)
'data.frame':	5716 obs. of  56 variables:
 $ FID       : int  0 1 2 3 4 5 6 7 8 9 ...
 $ OBJECTID  : int  1 2 3 4 5 6 7 8 9 10 ...
 $ AmbulanceR: chr  "Yes" "Yes" "Yes" "Yes" ...
 $ BikeAge_Gr: chr  "" "20-24" "30-39" "30-39" ...
 $ Bike_Age  : chr  "11" "20" "37" "30" ...
 $ Bike_Alc_D: chr  "No" "No" "No" "No" ...
 $ Bike_Dir  : chr  "With Traffic" "Facing Traffic" "" "With Traffic" ...
 $ Bike_Injur: chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ Bike_Pos  : chr  "Sidewalk / Crosswalk / Driveway Crossing" "Sidewalk / Crosswalk / Driveway Crossing" "Non-Roadway" "Travel Lane" ...
 $ Bike_Race : chr  "Black" "Hispanic" "Black" "White" ...
 $ Bike_Sex  : chr  "Male" "Male" "Male" "Male" ...
 $ City      : chr  "Durham" "Cary" "Stallings" "Salisbury" ...
 $ County    : chr  "Durham" "Wake" "Union" "Rowan" ...
 $ CrashAlcoh: chr  "No" "No" "No" "No" ...
 $ CrashDay  : chr  "Tuesday" "Friday" "Monday" "Friday" ...
 $ Crash_Date: chr  "01/02/2007 12:00:00 AM" "01/12/2007 12:00:00 AM" "01/15/2007 12:00:00 AM" "01/19/2007 12:00:00 AM" ...
 $ Crash_Grp : chr  "Parallel Paths - Other Circumstances" "Motorist Failed to Yield - Signalized Intersection" "Non-Roadway" "Motorist Left Turn / Merge" ...
 $ Crash_Hour: int  16 9 17 17 12 9 19 15 8 9 ...
 $ Crash_Loc : chr  "Non-Intersection" "Intersection" "Non-Roadway" "Intersection" ...
 $ Crash_Mont: chr  "January" "January" "January" "January" ...
 $ Crash_Time: chr  "16:41" "9:34" "17:55" "17:25" ...
 $ Crash_Type: chr  "Bicyclist Ride Out - Parallel Path" "Motorist Drive Out - Right Turn on Red" "Non-Roadway" "Motorist Left Turn - Opposite Direction" ...
 $ Crash_Ty_1: int  331225 132151 460910 111212 311235 131153 311231 111142 321239 211239 ...
 $ Crash_Year: int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...
 $ Crsh_Sevri: chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ Developmen: chr  "Residential" "Residential" "Commercial" "Commercial" ...
 $ DrvrAge_Gr: chr  "30-39" "60-69" "30-39" "" ...
 $ Drvr_Age  : chr  "35" "64" "39" "" ...
 $ Drvr_Alc_D: chr  "No" "No" "No" "No" ...
 $ Drvr_EstSp: chr  "31-35 mph" "0-5 mph" "6-10 mph" "31-35 mph" ...
 $ Drvr_Injur: chr  "O: No Injury" "O: No Injury" "O: No Injury" " Injury" ...
 $ Drvr_Race : chr  "White" "White" "White" "/Missing" ...
 $ Drvr_Sex  : chr  "Male" "Male" "Female" "" ...
 $ Drvr_VehTy: chr  "Passenger Car" "Passenger Car" "Passenger Car" "Sport Utility" ...
 $ ExcsSpdInd: chr  "No" "No" "No" "No" ...
 $ Hit_Run   : chr  "No" "No" "No" "Yes" ...
 $ Latitude  : num  36 35.8 35.1 35.7 35 ...
 $ Light_Cond: chr  "Daylight" "Daylight" "Dusk" "Daylight" ...
 $ Locality  : chr  "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" ...
 $ Longitude : num  -78.9 -78.8 -80.7 -80.5 -78.9 ...
 $ Num_Lanes : chr  "1 lane" "3 lanes" "2 lanes" "2 lanes" ...
 $ Num_Units : int  2 2 2 2 2 2 2 2 2 2 ...
 $ Rd_Charact: chr  "Straight - Level" "Straight - Grade" "Straight - Level" "Straight - Grade" ...
 $ Rd_Class  : chr  "Local Street" "Local Street" "Public Vehicular Area" "Local Street" ...
 $ Rd_Conditi: chr  "Dry" "Dry" "Dry" "Dry" ...
 $ Rd_Config : chr  "Two-Way, Divided, Unprotected Median" "Two-Way, Divided, Unprotected Median" "Two-Way, Not Divided" "Two-Way, Not Divided" ...
 $ Rd_Defects: chr  "None" "None" "None" "None" ...
 $ Rd_Feature: chr  "No Special Feature" "Four-Way Intersection" "No Special Feature" "Four-Way Intersection" ...
 $ Rd_Surface: chr  "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" ...
 $ Region    : chr  "Piedmont" "Piedmont" "Piedmont" "Piedmont" ...
 $ Rural_Urba: chr  "Urban" "Urban" "Urban" "Urban" ...
 $ Speed_Limi: chr  "30 - 35  MPH" "30 - 35  MPH" "20 - 25  MPH" "30 - 35  MPH" ...
 $ Traff_Cntr: chr  "No Control Present" "Stop And Go Signal" "No Control Present" "No Control Present" ...
 $ Weather   : chr  "Clear" "Clear" "Cloudy" "Cloudy" ...
 $ Workzone_I: chr  "No" "No" "No" "No" ...
 $ Location  : chr  "(36.03949, -78.883896)" "(35.751118, -78.7828)" "(35.084732, -80.69782)" "(35.6844, -80.47932)" ...
#
# ###################################################
# cleanData
#
names(cleanData)
 [1] "FID"           "OBJECTID"      "Ambulance"     "BikeAgeGroup"  "BikeAge"       "BikeAlcohol"   "BikeDirection"
 [8] "BikeInjury"    "BikePosition"  "BikeRace"      "BikeGender"    "City"          "County"        "CrashAlcoh"   
[15] "CrashDay"      "CrashDate"     "Crash_Grp"     "CrashHour"     "Crash_Loc"     "CrashMonth"    "CrashTime"    
[22] "Crash_Type"    "Crash_Ty_1"    "Crash_Year"    "Crsh_Sevri"    "Developmen"    "DrvrAge_Gr"    "Drvr_Age"     
[29] "DriverAlcohol" "Drvr_EstSp"    "Drvr_Injur"    "Drvr_Race"     "Drvr_Sex"      "Drvr_VehTy"    "ExcsSpdInd"   
[36] "Hit_Run"       "Latitude"      "Light_Cond"    "Locality"      "Longitude"     "Num_Lanes"     "Num_Units"    
[43] "Rd_Charact"    "Rd_Class"      "Rd_Conditi"    "Rd_Config"     "Rd_Defects"    "Rd_Feature"    "Rd_Surface"   
[50] "Region"        "Rural_Urba"    "Speed_Limi"    "Traff_Cntr"    "Weather"       "Workzone_I"    "Location" 
#
 names_cleanData <- names(cleanData)
#
str(cleanData)
'data.frame':	5716 obs. of  56 variables:
 $ FID          : int  0 1 2 3 4 5 6 7 8 9 ...
 $ OBJECTID     : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Ambulance    : chr  "Yes" "Yes" "Yes" "Yes" ...
 $ BikeAgeGroup : chr  "" "20-24" "30-39" "30-39" ...
 $ BikeAge      : chr  "11" "20" "37" "30" ...
 $ BikeAlcohol  : chr  "No" "No" "No" "No" ...
 $ BikeDirection: chr  "With Traffic" "Facing Traffic" "" "With Traffic" ...
 $ BikeInjury   : chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ BikePosition : chr  "Sidewalk / Crosswalk / Driveway Crossing" "Sidewalk / Crosswalk / Driveway Crossing" "Non-Roadway" "Travel Lane" ...
 $ BikeRace     : chr  "Black" "Hispanic" "Black" "White" ...
 $ BikeGender   : chr  "Male" "Male" "Male" "Male" ...
 $ City         : chr  "Durham" "Cary" "Stallings" "Salisbury" ...
 $ County       : chr  "Durham" "Wake" "Union" "Rowan" ...
 $ CrashAlcoh   : chr  "No" "No" "No" "No" ...
 $ CrashDay     : chr  "Tuesday" "Friday" "Monday" "Friday" ...
 $ CrashDate    : Date, format: "2007-01-02" "2007-01-12" "2007-01-15" "2007-01-19" ...
 $ Crash_Grp    : chr  "Parallel Paths - Other Circumstances" "Motorist Failed to Yield - Signalized Intersection" "Non-Roadway" "Motorist Left Turn / Merge" ...
 $ CrashHour    : int  16 9 17 17 12 9 19 15 8 9 ...
 $ Crash_Loc    : chr  "Non-Intersection" "Intersection" "Non-Roadway" "Intersection" ...
 $ CrashMonth   : chr  "January" "January" "January" "January" ...
 $ CrashTime    : POSIXct, format: "2007-12-31 16:41:00" "2007-12-31 09:34:00" "2007-12-31 17:55:00" "2007-12-31 17:25:00" ...
 $ Crash_Type   : chr  "Bicyclist Ride Out - Parallel Path" "Motorist Drive Out - Right Turn on Red" "Non-Roadway" "Motorist Left Turn - Opposite Direction" ...
 $ Crash_Ty_1   : int  331225 132151 460910 111212 311235 131153 311231 111142 321239 211239 ...
 $ Crash_Year   : int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...
 $ Crsh_Sevri   : chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ Developmen   : chr  "Residential" "Residential" "Commercial" "Commercial" ...
 $ DrvrAge_Gr   : chr  "30-39" "60-69" "30-39" "" ...
 $ Drvr_Age     : chr  "35" "64" "39" "" ...
 $ DriverAlcohol: chr  "No" "No" "No" "No" ...
 $ Drvr_EstSp   : chr  "31-35 mph" "0-5 mph" "6-10 mph" "31-35 mph" ...
 $ Drvr_Injur   : chr  "O: No Injury" "O: No Injury" "O: No Injury" " Injury" ...
 $ Drvr_Race    : chr  "White" "White" "White" "/Missing" ...
 $ Drvr_Sex     : chr  "Male" "Male" "Female" "" ...
 $ Drvr_VehTy   : chr  "Passenger Car" "Passenger Car" "Passenger Car" "Sport Utility" ...
 $ ExcsSpdInd   : chr  "No" "No" "No" "No" ...
 $ Hit_Run      : chr  "No" "No" "No" "Yes" ...
 $ Latitude     : num  36 35.8 35.1 35.7 35 ...
 $ Light_Cond   : chr  "Daylight" "Daylight" "Dusk" "Daylight" ...
 $ Locality     : chr  "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" ...
 $ Longitude    : num  -78.9 -78.8 -80.7 -80.5 -78.9 ...
 $ Num_Lanes    : chr  "1 lane" "3 lanes" "2 lanes" "2 lanes" ...
 $ Num_Units    : int  2 2 2 2 2 2 2 2 2 2 ...
 $ Rd_Charact   : chr  "Straight - Level" "Straight - Grade" "Straight - Level" "Straight - Grade" ...
 $ Rd_Class     : chr  "Local Street" "Local Street" "Public Vehicular Area" "Local Street" ...
 $ Rd_Conditi   : chr  "Dry" "Dry" "Dry" "Dry" ...
 $ Rd_Config    : chr  "Two-Way, Divided, Unprotected Median" "Two-Way, Divided, Unprotected Median" "Two-Way, Not Divided" "Two-Way, Not Divided" ...
 $ Rd_Defects   : chr  "None" "None" "None" "None" ...
 $ Rd_Feature   : chr  "No Special Feature" "Four-Way Intersection" "No Special Feature" "Four-Way Intersection" ...
 $ Rd_Surface   : chr  "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" ...
 $ Region       : chr  "Piedmont" "Piedmont" "Piedmont" "Piedmont" ...
 $ Rural_Urba   : chr  "Urban" "Urban" "Urban" "Urban" ...
 $ Speed_Limi   : chr  "30 - 35  MPH" "30 - 35  MPH" "20 - 25  MPH" "30 - 35  MPH" ...
 $ Traff_Cntr   : chr  "No Control Present" "Stop And Go Signal" "No Control Present" "No Control Present" ...
 $ Weather      : chr  "Clear" "Clear" "Cloudy" "Cloudy" ...
 $ Workzone_I   : chr  "No" "No" "No" "No" ...
 $ Location     : chr  "(36.03949, -78.883896)" "(35.751118, -78.7828)" "(35.084732, -80.69782)" "(35.6844, -80.47932)" ..
 #
 # ===================================================================================
 #
 # looking at some data values
 #
 plyr::count(rawData, vars="BikeAgeGroup")
    BikeAgeGroup freq
1                112
2           0-5   60
3        10-Jun  421
4        15-Nov  747
5         16-19  605
6         20-24  680
7         25-29  430
8         30-39  658
9         40-49  920
10        50-59  739
11        60-69  274
12           70   12
13          70+   58
#