# ############################################
# David Hopp
# 4/21/2016
#
# CodeForDurham
# bicycle accident data
#
##############################################
# script_A02_explore.r
# data exploration
# look at categorical data and see if any "odd" entries
# ############################################
#
#rawData categorical variables (columns) - keeping row number OBJECTID - are:
catcol_rawData <- c("OBJECTID", "AmbulanceR","BikeAge_Gr","Bike_Alc_D","Bike_Dir","Bike_Injur","Bike_Pos",
"Bike_Race","Bike_Sex","City","County","CrashAlcoh","CrashDay","Crash_Grp","Crash_Hour",
"Crash_Loc","Crash_Mont","Crash_Type","Crash_Ty_1","Crash_Year","Crsh_Sevri","Developmen","DrvrAge_Gr",
"Drvr_Age","Drvr_Alc_D","Drvr_EstSp","Drvr_Injur","Drvr_Race","Drvr_Sex","Drvr_VehTy","ExcsSpdInd","Hit_Run",
"Light_Cond","Locality","Num_Lanes","Num_Units","Rd_Charact","Rd_Class","Rd_Conditi",
"Rd_Config","Rd_Defects","Rd_Feature","Rd_Surface","Region","Rural_Urba","Speed_Limi","Traff_Cntr","Weather",
"Workzone_I" )
#
# work with only the categorical columns
rawData_cat <- dplyr::select( rawData, one_of(catcol_rawData) )
#
str(rawData_cat)
'data.frame':	5716 obs. of  49 variables:
 $ OBJECTID  : int  1 2 3 4 5 6 7 8 9 10 ...
 $ AmbulanceR: chr  "Yes" "Yes" "Yes" "Yes" ...
 $ BikeAge_Gr: chr  "" "20-24" "30-39" "30-39" ...
 $ Bike_Alc_D: chr  "No" "No" "No" "No" ...
 $ Bike_Dir  : chr  "With Traffic" "Facing Traffic" "" "With Traffic" ...
 $ Bike_Injur: chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ Bike_Pos  : chr  "Sidewalk / Crosswalk / Driveway Crossing" "Sidewalk / Crosswalk / Driveway Crossing" "Non-Roadway" "Travel Lane" ...
 $ Bike_Race : chr  "Black" "Hispanic" "Black" "White" ...
 $ Bike_Sex  : chr  "Male" "Male" "Male" "Male" ...
 $ City      : chr  "Durham" "Cary" "Stallings" "Salisbury" ...
 $ County    : chr  "Durham" "Wake" "Union" "Rowan" ...
 $ CrashAlcoh: chr  "No" "No" "No" "No" ...
 $ CrashDay  : chr  "Tuesday" "Friday" "Monday" "Friday" ...
 $ Crash_Grp : chr  "Parallel Paths - Other Circumstances" "Motorist Failed to Yield - Signalized Intersection" "Non-Roadway" "Motorist Left Turn / Merge" ...
 $ Crash_Hour: int  16 9 17 17 12 9 19 15 8 9 ...
 $ Crash_Loc : chr  "Non-Intersection" "Intersection" "Non-Roadway" "Intersection" ...
 $ Crash_Mont: chr  "January" "January" "January" "January" ...
 $ Crash_Type: chr  "Bicyclist Ride Out - Parallel Path" "Motorist Drive Out - Right Turn on Red" "Non-Roadway" "Motorist Left Turn - Opposite Direction" ...
 $ Crash_Ty_1: int  331225 132151 460910 111212 311235 131153 311231 111142 321239 211239 ...
 $ Crash_Year: int  2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...
 $ Crsh_Sevri: chr  "B: Evident Injury" "C: Possible Injury" "B: Evident Injury" "C: Possible Injury" ...
 $ Developmen: chr  "Residential" "Residential" "Commercial" "Commercial" ...
 $ DrvrAge_Gr: chr  "30-39" "60-69" "30-39" "" ...
 $ Drvr_Age  : chr  "35" "64" "39" "" ...
 $ Drvr_Alc_D: chr  "No" "No" "No" "No" ...
 $ Drvr_EstSp: chr  "31-35 mph" "0-5 mph" "6-10 mph" "31-35 mph" ...
 $ Drvr_Injur: chr  "O: No Injury" "O: No Injury" "O: No Injury" " Injury" ...
 $ Drvr_Race : chr  "White" "White" "White" "/Missing" ...
 $ Drvr_Sex  : chr  "Male" "Male" "Female" "" ...
 $ Drvr_VehTy: chr  "Passenger Car" "Passenger Car" "Passenger Car" "Sport Utility" ...
 $ ExcsSpdInd: chr  "No" "No" "No" "No" ...
 $ Hit_Run   : chr  "No" "No" "No" "Yes" ...
 $ Light_Cond: chr  "Daylight" "Daylight" "Dusk" "Daylight" ...
 $ Locality  : chr  "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" "Urban (>70% Developed)" ...
 $ Num_Lanes : chr  "1 lane" "3 lanes" "2 lanes" "2 lanes" ...
 $ Num_Units : int  2 2 2 2 2 2 2 2 2 2 ...
 $ Rd_Charact: chr  "Straight - Level" "Straight - Grade" "Straight - Level" "Straight - Grade" ...
 $ Rd_Class  : chr  "Local Street" "Local Street" "Public Vehicular Area" "Local Street" ...
 $ Rd_Conditi: chr  "Dry" "Dry" "Dry" "Dry" ...
 $ Rd_Config : chr  "Two-Way, Divided, Unprotected Median" "Two-Way, Divided, Unprotected Median" "Two-Way, Not Divided" "Two-Way, Not Divided" ...
 $ Rd_Defects: chr  "None" "None" "None" "None" ...
 $ Rd_Feature: chr  "No Special Feature" "Four-Way Intersection" "No Special Feature" "Four-Way Intersection" ...
 $ Rd_Surface: chr  "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" "Smooth Asphalt" ...
 $ Region    : chr  "Piedmont" "Piedmont" "Piedmont" "Piedmont" ...
 $ Rural_Urba: chr  "Urban" "Urban" "Urban" "Urban" ...
 $ Speed_Limi: chr  "30 - 35  MPH" "30 - 35  MPH" "20 - 25  MPH" "30 - 35  MPH" ...
 $ Traff_Cntr: chr  "No Control Present" "Stop And Go Signal" "No Control Present" "No Control Present" ...
 $ Weather   : chr  "Clear" "Clear" "Cloudy" "Cloudy" ...
 $ Workzone_I: chr  "No" "No" "No" "No" ...
 #
 # ############################################################
 #
 # compute the values and counts of the categorical columns
 # these will require visual review to identify any odd entries
 #
 rawData_catmelt <- reshape2::melt(rawData_cat,id="OBJECTID")
 rawData_catcount <- plyr::count( rawData_catmelt, vars=c("variable","value") )
 #
 nrow(rawData_catmelt)
 [1] 274368
 nrow(rawData_catcount)
 [1] 1395
 # ############################################################
 